/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecondOpinionRouteImport } from './routes/second-opinion'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecondOpinionIndexRouteImport } from './routes/second-opinion.index'
import { Route as PartnershipsIndexRouteImport } from './routes/partnerships.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SecondOpinionApplyRouteImport } from './routes/second-opinion.apply'
import { Route as PartnershipsApplyRouteImport } from './routes/partnerships.apply'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminAuthenticatedPricingRouteImport } from './routes/admin/_authenticated/pricing'
import { Route as AdminAuthenticatedDashboardRouteImport } from './routes/admin/_authenticated/dashboard'

const SecondOpinionRoute = SecondOpinionRouteImport.update({
  id: '/second-opinion',
  path: '/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionIndexRoute = SecondOpinionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecondOpinionRoute,
} as any)
const PartnershipsIndexRoute = PartnershipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnershipsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SecondOpinionApplyRoute = SecondOpinionApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => SecondOpinionRoute,
} as any)
const PartnershipsApplyRoute = PartnershipsApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PartnershipsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticatedPricingRoute =
  AdminAuthenticatedPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedDashboardRoute =
  AdminAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/partnerships': typeof PartnershipsRouteWithChildren
  '/second-opinion': typeof SecondOpinionRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/partnerships/apply': typeof PartnershipsApplyRoute
  '/second-opinion/apply': typeof SecondOpinionApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/second-opinion/': typeof SecondOpinionIndexRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/pricing': typeof AdminAuthenticatedPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/partnerships/apply': typeof PartnershipsApplyRoute
  '/second-opinion/apply': typeof SecondOpinionApplyRoute
  '/partnerships': typeof PartnershipsIndexRoute
  '/second-opinion': typeof SecondOpinionIndexRoute
  '/admin/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/pricing': typeof AdminAuthenticatedPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/partnerships': typeof PartnershipsRouteWithChildren
  '/second-opinion': typeof SecondOpinionRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/partnerships/apply': typeof PartnershipsApplyRoute
  '/second-opinion/apply': typeof SecondOpinionApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/second-opinion/': typeof SecondOpinionIndexRoute
  '/admin/_authenticated/dashboard': typeof AdminAuthenticatedDashboardRoute
  '/admin/_authenticated/pricing': typeof AdminAuthenticatedPricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/partnerships'
    | '/second-opinion'
    | '/admin/login'
    | '/partnerships/apply'
    | '/second-opinion/apply'
    | '/admin/'
    | '/partnerships/'
    | '/second-opinion/'
    | '/admin/dashboard'
    | '/admin/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/partnerships/apply'
    | '/second-opinion/apply'
    | '/partnerships'
    | '/second-opinion'
    | '/admin/dashboard'
    | '/admin/pricing'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/partnerships'
    | '/second-opinion'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/partnerships/apply'
    | '/second-opinion/apply'
    | '/admin/'
    | '/partnerships/'
    | '/second-opinion/'
    | '/admin/_authenticated/dashboard'
    | '/admin/_authenticated/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PartnershipsRoute: typeof PartnershipsRouteWithChildren
  SecondOpinionRoute: typeof SecondOpinionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/second-opinion': {
      id: '/second-opinion'
      path: '/second-opinion'
      fullPath: '/second-opinion'
      preLoaderRoute: typeof SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinion/': {
      id: '/second-opinion/'
      path: '/'
      fullPath: '/second-opinion/'
      preLoaderRoute: typeof SecondOpinionIndexRouteImport
      parentRoute: typeof SecondOpinionRoute
    }
    '/partnerships/': {
      id: '/partnerships/'
      path: '/'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof PartnershipsIndexRouteImport
      parentRoute: typeof PartnershipsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/second-opinion/apply': {
      id: '/second-opinion/apply'
      path: '/apply'
      fullPath: '/second-opinion/apply'
      preLoaderRoute: typeof SecondOpinionApplyRouteImport
      parentRoute: typeof SecondOpinionRoute
    }
    '/partnerships/apply': {
      id: '/partnerships/apply'
      path: '/apply'
      fullPath: '/partnerships/apply'
      preLoaderRoute: typeof PartnershipsApplyRouteImport
      parentRoute: typeof PartnershipsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authenticated/pricing': {
      id: '/admin/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminAuthenticatedPricingRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/dashboard': {
      id: '/admin/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthenticatedDashboardRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedDashboardRoute: typeof AdminAuthenticatedDashboardRoute
  AdminAuthenticatedPricingRoute: typeof AdminAuthenticatedPricingRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedDashboardRoute: AdminAuthenticatedDashboardRoute,
  AdminAuthenticatedPricingRoute: AdminAuthenticatedPricingRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartnershipsRouteChildren {
  PartnershipsApplyRoute: typeof PartnershipsApplyRoute
  PartnershipsIndexRoute: typeof PartnershipsIndexRoute
}

const PartnershipsRouteChildren: PartnershipsRouteChildren = {
  PartnershipsApplyRoute: PartnershipsApplyRoute,
  PartnershipsIndexRoute: PartnershipsIndexRoute,
}

const PartnershipsRouteWithChildren = PartnershipsRoute._addFileChildren(
  PartnershipsRouteChildren,
)

interface SecondOpinionRouteChildren {
  SecondOpinionApplyRoute: typeof SecondOpinionApplyRoute
  SecondOpinionIndexRoute: typeof SecondOpinionIndexRoute
}

const SecondOpinionRouteChildren: SecondOpinionRouteChildren = {
  SecondOpinionApplyRoute: SecondOpinionApplyRoute,
  SecondOpinionIndexRoute: SecondOpinionIndexRoute,
}

const SecondOpinionRouteWithChildren = SecondOpinionRoute._addFileChildren(
  SecondOpinionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PartnershipsRoute: PartnershipsRouteWithChildren,
  SecondOpinionRoute: SecondOpinionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
